Create/buy/product/endpoint
HAL-IAIH-team-F/hew-back pull request #45
Opened 2024-10-28 22:34 UTC by yamadacojp27

【create buy-product-endpoint #29】
JWTtokenからユーザーID取り出して、ログインしているユーザーが自身の商品カート、商品カートから購入状態に・・・というタスクはできた。が、テスト検証ができない。

【お願いしたいこと】

１．そもそも今回の場合、何のテストをしたらいいか分からなかったので、
・何を目的で
・手順はどのように
・どこの関数を使うべきなのか
を知りたいので、できれば対面で教えて欲しい
(# テスト検証として、
# ダミーデータを渡してあげて、それが返ってくるか？)

２．次のタスクのcreate recruit creator endpointについて
・僕の解釈が合っているかのすり合わせ
・どのように作るべきかを教えて欲しい

ちなみに、postmanでの検証でexpは必要でした(要らない方法あるかもだけど、分からなかった)

一旦、プルリク送ります！
今日か明後日に教えてもらえれば

2024-11-08 05:13 UTC, yamadacojp27 commented on src/test/product_test.py
>  async def test_read_products(client, session,product_table_saved):
a

2024-11-13 16:12 UTC, kigawa01 commented
ブランチの先にfeature/つけて............

2024-11-13 16:12 UTC, kigawa01 commented
`.env.test`はコミットしないでほしい
.gitignoreに書いとくと除外できる

2024-11-13 16:21 UTC, kigawa01 requested changes

2024-11-13 16:21 UTC, kigawa01 commented on src/hew_back/tables/__cart_product.py
> +from sqlalchemy.testing.suite.test_reflection import users
編なのインポートしててエラーの原因になってる

2024-11-13 16:21 UTC, kigawa01 commented on src/test/__init__.py
> +dotenv.load_dotenv("../.env.test")
ファイルパスおかしくなってる

2024-11-13 16:21 UTC, kigawa01 commented on src/test/conftest.py
> +        yield client
http://testserver
って何？

2024-11-13 16:21 UTC, kigawa01 commented on src/test/conftest.py
> +async def async_client(app):
上にあるclientで動くはず

2024-11-14 04:28 UTC, yamadacojp27 commented on src/test/cart_product_test.py
> +async def test_read_cart_product(
1

2024-11-24 14:28 UTC, closed without merging