Feature/crete find produtc endpoint
HAL-IAIH-team-F/hew-back pull request #51
Opened 2024-11-21 14:28 UTC by yamadacojp27

本当は

create/buy/product/endpoint

！！！！

2024-11-22 00:11 UTC, kigawa01 commented
なんかもう一個PRあるからこっちのPR使うね

2024-11-23 07:45 UTC, kigawa01 requested changes

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/responses/__init__.py
このファイル消したい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart.py
> +    cart_id = Column(UUID(as_uuid=True), primary_key=True)
defaultつけたい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +    async def get_cart_product(
リストを返す関数だから最後複数形にしたい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +    ):
型書いといてほしい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +            user_id: uuid.UUID,
usertableにしたい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +    async def put_cart_product(
何してるのかわかるような名前にしたい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +        user_id: uuid.UUID,
usertableにしたい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__cart_product.py
> +    ):
型欲しい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__chat_image_table.py
> +        tbls: list[ChatImageTable] = []
tblsは名前が被るからtablesに戻しといてほしい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__chat_table.py
> +        tbls: list[ChatTable] = []
tblsは名前が被るからtablesに戻しといてほしい

2024-11-23 07:45 UTC, kigawa01 commented on src/hew_back/tbls/__chat_user_table.py
> +        tbls: list[ChatUserTable] = []
tblsは名前が被るからtablesに戻しといてほしい

2024-11-23 07:45 UTC, kigawa01 commented on src/test/__init__.py
> +# dotenv.load_dotenv("./.env.local")
戻しといて

2024-11-23 15:14 UTC, yamadacojp27 commented on src/hew_back/api/__init__.py
> +
ok

2024-11-24 08:01 UTC, yamadacojp27 commented on src/hew_back/responses/__init__.py
ひとまず移動＆GetProductsResponseと同じ機能が__finderがあったので、(GetProductsResponse)をコメントアウトしました。

2024-11-24 10:49 UTC, yamadacojp27 commented on src/hew_back/product/cart_product_api.py
> +     )
・・・

2024-11-24 12:38 UTC, yamadacojp27 commented on src/test/cart_product_test.py
> +async def test_read_product_cart(
a

2024-12-01 12:04 UTC, merged